### ISSUE TITLE
Running error: demo path, unparsed argument is detected

### ISSUE THREAD

**Issue by TPEmist** [clvrai/skill-chaining#5]
error log:
```
user@user:~/skill-chaining$ mpirun -np 4 python3 -m run --algo ppo --furniture_name table_lack_0825 --demo_path demos/table_lack/ --num_connects 4 --max_episode_steps 800 --max_global_step 200000000 --run_prefix ppo
Invalid MIT-MAGIC-COOKIE-1 keypybullet build time: Feb 28 2022 22:32:49
/usr/local/lib/python3.8/dist-packages/ale_py/roms/__init__.py:94: DeprecationWarning: Automatic importing of atari-py roms won't be supported in future releases of ale-py. Please migrate over to using `ale-import-roms` OR an ALE-supported ROM package. To make this warning disappear you can run `ale-import-roms --import-from-pkg atari_py.atari_roms`.For more information see: https://github.com/mgbellemare/Arcade-Learning-Environment#rom-management
  _RESOLVED_ROMS = _resolve_roms()
[2022-05-01 22:22:52,277] Unparsed argument is detected:
['--demo_path', 'demos/table_lack/']
pybullet build time: Feb 28 2022 22:32:49
/usr/local/lib/python3.8/dist-packages/ale_py/roms/__init__.py:94: DeprecationWarning: Automatic importing of atari-py roms won't be supported in future releases of ale-py. Please migrate over to using `ale-import-roms` OR an ALE-supported ROM package. To make this warning disappear you can run `ale-import-roms --import-from-pkg atari_py.atari_roms`.For more information see: https://github.com/mgbellemare/Arcade-Learning-Environment#rom-management
  _RESOLVED_ROMS = _resolve_roms()
[2022-05-01 22:22:52,545] Unparsed argument is detected:
['--demo_path', 'demos/table_lack/']
pybullet build time: Feb 28 2022 22:32:49
/usr/local/lib/python3.8/dist-packages/ale_py/roms/__init__.py:94: DeprecationWarning: Automatic importing of atari-py roms won't be supported in future releases of ale-py. Please migrate over to using `ale-import-roms` OR an ALE-supported ROM package. To make this warning disappear you can run `ale-import-roms --import-from-pkg atari_py.atari_roms`.For more information see: https://github.com/mgbellemare/Arcade-Learning-Environment#rom-management
  _RESOLVED_ROMS = _resolve_roms()
[2022-05-01 22:22:52,705] Unparsed argument is detected:
['--demo_path', 'demos/table_lack/']
pybullet build time: Feb 28 2022 22:32:49
/usr/local/lib/python3.8/dist-packages/ale_py/roms/__init__.py:94: DeprecationWarning: Automatic importing of atari-py roms won't be supported in future releases of ale-py. Please migrate over to using `ale-import-roms` OR an ALE-supported ROM package. To make this warning disappear you can run `ale-import-roms --import-from-pkg atari_py.atari_roms`.For more information see: https://github.com/mgbellemare/Arcade-Learning-Environment#rom-management
  _RESOLVED_ROMS = _resolve_roms()
[2022-05-01 22:22:52,995] Unparsed argument is detected:
['--demo_path', 'demos/table_lack/']
```

I first ran the command:
`# Sub-task demo generation`
```
$ python -m furniture.env.furniture_sawyer_gen --furniture_name table_lack_0825 --demo_dir demos/table_lack/ --reset_robot_after_attach True --max_episode_steps 200 --num_connects 1 --n_demos 200 --start_count 0 --phase_ob True
```

and got the folder demos/table_lack with lots of Sawyer_table_lack_0825_xxx.pkl files

then run the command:
```
$ mpirun -np 4 python3 -m run --algo ppo --furniture_name table_lack_0825 --demo_path demos/table_lack/ --num_connects 4 --max_episode_steps 800 --max_global_step 200000000 --run_prefix ppo
```

and I ran into the error metioned above, what's the demo_path trying to get? did I miss anything? or I'm running to other problem? Thanks

**Comment by youngwoon** [comment]
Sorry for the confusing use of `--demo_path`. The `--demo_path` should contain a prefix of file names, e.g. `--demo_path demos/table_lack/Sawyer`. This is designed for the use a partition of demos, e.g. `Sawyer_table_lack_0825_0` for part 0 and `Sawyer_table_lack_0825_1` for part 1.

**Comment by TPEmist** [comment]
with my folder like skill_chaining / demos / table_lack / Sawyer_table_lack_0825_xxx.pkl files
In skill_chaining folder I ran: 
```
mpirun -np 4 python3 -m run --algo ppo --furniture_name table_lack_0825 --demo_path demos/table_lack/Sawyer --num_connects 4 --max_episode_steps 800 --max_global_step 200000000 --run_prefix ppo
```

Still getting error:
```
Invalid MIT-MAGIC-COOKIE-1 keypybullet build time: Feb 28 2022 22:32:49
pybullet build time: Feb 28 2022 22:32:49
/usr/local/lib/python3.8/dist-packages/ale_py/roms/__init__.py:94: DeprecationWarning: Automatic importing of atari-py roms won't be supported in future releases of ale-py. Please migrate over to using `ale-import-roms` OR an ALE-supported ROM package. To make this warning disappear you can run `ale-import-roms --import-from-pkg atari_py.atari_roms`.For more information see: https://github.com/mgbellemare/Arcade-Learning-Environment#rom-management
  _RESOLVED_ROMS = _resolve_roms()
[2022-05-03 16:10:40,853] Unparsed argument is detected:
['--demo_path', 'demos/table_lack/Sawyer']
/usr/local/lib/python3.8/dist-packages/ale_py/roms/__init__.py:94: DeprecationWarning: Automatic importing of atari-py roms won't be supported in future releases of ale-py. Please migrate over to using `ale-import-roms` OR an ALE-supported ROM package. To make this warning disappear you can run `ale-import-roms --import-from-pkg atari_py.atari_roms`.For more information see: https://github.com/mgbellemare/Arcade-Learning-Environment#rom-management
  _RESOLVED_ROMS = _resolve_roms()
[2022-05-03 16:10:40,858] Unparsed argument is detected:
['--demo_path', 'demos/table_lack/Sawyer']
pybullet build time: Feb 28 2022 22:32:49
/usr/local/lib/python3.8/dist-packages/ale_py/roms/__init__.py:94: DeprecationWarning: Automatic importing of atari-py roms won't be supported in future releases of ale-py. Please migrate over to using `ale-import-roms` OR an ALE-supported ROM package. To make this warning disappear you can run `ale-import-roms --import-from-pkg atari_py.atari_roms`.For more information see: https://github.com/mgbellemare/Arcade-Learning-Environment#rom-management
  _RESOLVED_ROMS = _resolve_roms()
[2022-05-03 16:10:41,159] Unparsed argument is detected:
['--demo_path', 'demos/table_lack/Sawyer']
pybullet build time: Feb 28 2022 22:32:49
/usr/local/lib/python3.8/dist-packages/ale_py/roms/__init__.py:94: DeprecationWarning: Automatic importing of atari-py roms won't be supported in future releases of ale-py. Please migrate over to using `ale-import-roms` OR an ALE-supported ROM package. To make this warning disappear you can run `ale-import-roms --import-from-pkg atari_py.atari_roms`.For more information see: https://github.com/mgbellemare/Arcade-Learning-Environment#rom-management
  _RESOLVED_ROMS = _resolve_roms()
[2022-05-03 16:10:41,383] Unparsed argument is detected:
['--demo_path', 'demos/table_lack/Sawyer']
```

did i do something wrong?

**Comment by youngwoon** [comment]
I think you are running `PPO` and it does not require demonstrations. Thus, you need to remove `--demo_path`. Sorry for the confusion. I updated README accordingly.

**Comment by TPEmist** [comment]
* 19:54 UPDATE > I update the gym version to gym-0.23.1 and got no error. Thanks!
-----------------------------------------------------------------------------------
Thank you for your quick reply !
So I ran it without `--demo_path` like this:
```
mpirun -np 4 python3 -m run --algo ppo --furniture_name table_lack_0825 --num_connects 4 --max_episode_steps 800 --max_global_step 200000000 --run_prefix ppo
```
Getting another error, did I miss anything? 
I think it might be a gym version problem maybe? what version are you using?
Error log:
```
Invalid MIT-MAGIC-COOKIE-1 keypybullet build time: Feb 28 2022 22:32:49
/usr/local/lib/python3.8/dist-packages/ale_py/roms/__init__.py:94: DeprecationWarning: Automatic importing of atari-py roms won't be supported in future releases of ale-py. Please migrate over to using `ale-import-roms` OR an ALE-supported ROM package. To make this warning disappear you can run `ale-import-roms --import-from-pkg atari_py.atari_roms`.For more information see: https://github.com/mgbellemare/Arcade-Learning-Environment#rom-management
  _RESOLVED_ROMS = _resolve_roms()
[2022-05-03 19:44:40,564] Run a base worker.
[2022-05-03 19:44:40,565] Create log directory: log/table_lack_0825.ppo.ppo.123
[2022-05-03 19:44:40,565] Create video directory: log/table_lack_0825.ppo.ppo.123/video
[2022-05-03 19:44:40,565] Create demo directory: log/table_lack_0825.ppo.ppo.123/demo
[2022-05-03 19:44:40,747] Store parameters in log/table_lack_0825.ppo.ppo.123/params.json
pybullet build time: Feb 28 2022 22:32:49
/usr/local/lib/python3.8/dist-packages/ale_py/roms/__init__.py:94: DeprecationWarning: Automatic importing of atari-py roms won't be supported in future releases of ale-py. Please migrate over to using `ale-import-roms` OR an ALE-supported ROM package. To make this warning disappear you can run `ale-import-roms --import-from-pkg atari_py.atari_roms`.For more information see: https://github.com/mgbellemare/Arcade-Learning-Environment#rom-management
  _RESOLVED_ROMS = _resolve_roms()
[2022-05-03 19:44:40,840] Run worker 3 and disable logger.
pybullet build time: Feb 28 2022 22:32:49
/usr/local/lib/python3.8/dist-packages/ale_py/roms/__init__.py:94: DeprecationWarning: Automatic importing of atari-py roms won't be supported in future releases of ale-py. Please migrate over to using `ale-import-roms` OR an ALE-supported ROM package. To make this warning disappear you can run `ale-import-roms --import-from-pkg atari_py.atari_roms`.For more information see: https://github.com/mgbellemare/Arcade-Learning-Environment#rom-management
  _RESOLVED_ROMS = _resolve_roms()
[2022-05-03 19:44:40,997] Run worker 1 and disable logger.
pybullet build time: Feb 28 2022 22:32:49
/usr/local/lib/python3.8/dist-packages/ale_py/roms/__init__.py:94: DeprecationWarning: Automatic importing of atari-py roms won't be supported in future releases of ale-py. Please migrate over to using `ale-import-roms` OR an ALE-supported ROM package. To make this warning disappear you can run `ale-import-roms --import-from-pkg atari_py.atari_roms`.For more information see: https://github.com/mgbellemare/Arcade-Learning-Environment#rom-management
  _RESOLVED_ROMS = _resolve_roms()
[2022-05-03 19:44:41,214] Run worker 2 and disable logger.
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/tpemist/skill-chaining/run.py", line 43, in <module>
    SkillChainingRun(parser).run()
  File "/home/tpemist/skill-chaining/method/robot_learning/main.py", line 140, in run
    trainer = self._get_trainer()
  File "/home/tpemist/skill-chaining/run.py", line 26, in _get_trainer
    return super()._get_trainer()
  File "/home/tpemist/skill-chaining/method/robot_learning/main.py", line 136, in _get_trainer
    return Trainer(self._config)
  File "/home/tpemist/skill-chaining/method/robot_learning/trainer.py", line 41, in __init__
    self._env = make_env(config.env, config)
  File "/home/tpemist/skill-chaining/method/robot_learning/environments/__init__.py", line 24, in make_env
    return get_gym_env(name, config)
  File "/home/tpemist/skill-chaining/method/robot_learning/environments/__init__.py", line 52, in get_gym_env
    env = GymWrapper(
  File "/home/tpemist/skill-chaining/method/robot_learning/utils/gym_env.py", line 97, in __init__
    max_episode_steps = self.env.spec.kwargs["max_episode_steps"]
AttributeError: 'EnvSpec' object has no attribute 'kwargs'
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/tpemist/skill-chaining/run.py", line 43, in <module>
    SkillChainingRun(parser).run()
  File "/home/tpemist/skill-chaining/method/robot_learning/main.py", line 140, in run
    trainer = self._get_trainer()
  File "/home/tpemist/skill-chaining/run.py", line 26, in _get_trainer
    return super()._get_trainer()
  File "/home/tpemist/skill-chaining/method/robot_learning/main.py", line 136, in _get_trainer
    return Trainer(self._config)
  File "/home/tpemist/skill-chaining/method/robot_learning/trainer.py", line 41, in __init__
    self._env = make_env(config.env, config)
  File "/home/tpemist/skill-chaining/method/robot_learning/environments/__init__.py", line 24, in make_env
    return get_gym_env(name, config)
  File "/home/tpemist/skill-chaining/method/robot_learning/environments/__init__.py", line 52, in get_gym_env
    env = GymWrapper(
  File "/home/tpemist/skill-chaining/method/robot_learning/utils/gym_env.py", line 97, in __init__
    max_episode_steps = self.env.spec.kwargs["max_episode_steps"]
AttributeError: 'EnvSpec' object has no attribute 'kwargs'
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/tpemist/skill-chaining/run.py", line 43, in <module>
    SkillChainingRun(parser).run()
  File "/home/tpemist/skill-chaining/method/robot_learning/main.py", line 140, in run
    trainer = self._get_trainer()
  File "/home/tpemist/skill-chaining/run.py", line 26, in _get_trainer
    return super()._get_trainer()
  File "/home/tpemist/skill-chaining/method/robot_learning/main.py", line 136, in _get_trainer
    return Trainer(self._config)
  File "/home/tpemist/skill-chaining/method/robot_learning/trainer.py", line 41, in __init__
    self._env = make_env(config.env, config)
  File "/home/tpemist/skill-chaining/method/robot_learning/environments/__init__.py", line 24, in make_env
    return get_gym_env(name, config)
  File "/home/tpemist/skill-chaining/method/robot_learning/environments/__init__.py", line 52, in get_gym_env
    env = GymWrapper(
  File "/home/tpemist/skill-chaining/method/robot_learning/utils/gym_env.py", line 97, in __init__
    max_episode_steps = self.env.spec.kwargs["max_episode_steps"]
AttributeError: 'EnvSpec' object has no attribute 'kwargs'
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/tpemist/skill-chaining/run.py", line 43, in <module>
    SkillChainingRun(parser).run()
  File "/home/tpemist/skill-chaining/method/robot_learning/main.py", line 140, in run
    trainer = self._get_trainer()
  File "/home/tpemist/skill-chaining/run.py", line 26, in _get_trainer
    return super()._get_trainer()
  File "/home/tpemist/skill-chaining/method/robot_learning/main.py", line 136, in _get_trainer
    return Trainer(self._config)
  File "/home/tpemist/skill-chaining/method/robot_learning/trainer.py", line 41, in __init__
    self._env = make_env(config.env, config)
  File "/home/tpemist/skill-chaining/method/robot_learning/environments/__init__.py", line 24, in make_env
    return get_gym_env(name, config)
  File "/home/tpemist/skill-chaining/method/robot_learning/environments/__init__.py", line 52, in get_gym_env
    env = GymWrapper(
  File "/home/tpemist/skill-chaining/method/robot_learning/utils/gym_env.py", line 97, in __init__
    max_episode_steps = self.env.spec.kwargs["max_episode_steps"]
AttributeError: 'EnvSpec' object has no attribute 'kwargs'
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[35163,1],3]
  Exit code:    1
```
